Generico lifting testuale
carmelolg/it-pragmatic-programmer pull request #2
Opened 2021-01-27 16:27 UTC by ZinRicky

* Riassettata la punteggiatura. In particolare, inserite le virgolette caporali direttamente nel codice.
* Cambiato qualche accento.
* Proposta qualche modifica sintattica.

2021-01-27 16:48 UTC, carmelolg requested changes
Grazie mille per le tue modifiche, ti chiedo gentilmente di allegare alla Pull Request anche la modifica ai file .tex, principale fonte del documento.
E' possibile?

2021-01-27 17:42 UTC, ZinRicky commented
Tra adesso e dopo cena dovrei riuscire a farlo

2021-01-28 11:29 UTC, ZinRicky commented
Dovrebbe essere a posto, adesso

2021-01-28 13:34 UTC, carmelolg requested changes
Mi servirà un pò di tempo per fare la review, in ogni caso su qualcosa non sono d'accordo. 
Non va bene ad esempio togliere l'enfatizzazione alle parole inglesi in un testo italiano. Mi prendo alcuni giorni per revisionare ma penso di essere propenso a rifiutare la patch.

Ti chiedo, se possibile, di segnalarmi sezione per sezione le modifiche che ritieni assolutamente necessarie in modo da fare una review incrementale e discuterne insieme.

Grazie mille

2021-01-28 13:34 UTC, carmelolg commented on README.md
> -Un buon modo per iniziare questo articolo è sicuramente spiegarne le motivazioni.
Perché toglierlo?

2021-01-28 14:26 UTC, ZinRicky commented on README.md
> -Un buon modo per iniziare questo articolo è sicuramente spiegarne le motivazioni.
L’ho tolto perché non aggiunge nulla rispetto al capoverso sotto: iniziare dal secondo capoverso risulta molto più d’impatto e rende vera la frase rimossa. Se, infatti, si inizia con quella frase, non si sta iniziando con le motivazioni alla stesura, ma con una considerazione paratestuale.

Non so se abbia un nome, ma esiste una massima che fa: «Se devi dire una cosa, dilla». L’attacco di questa guida, se privato della prima frase, rispetta meglio questa norma.

2021-01-28 14:32 UTC, ZinRicky commented
> Non va bene togliere l'enfatizzazione alle parole inglesi in un testo italiano.

Sono d’accordo; ti devo una spiegazione sul perché le ho rimosse. Alcuni anglismi nella guida originale sono enfatizzati, mentre altri no: *software* non è enfatizzato, mentre *software architect* lo è. Consiglierei di applicare uno standard unico, visto che per la maggior parte si tratta di parole tecniche o di origine specialistica; non sapendo se enfatizzare tutto o non enfatizzare nulla, ho scelto quest’ultima, pur sapendo che avresti potuto preferire l’altra opzione.

> Ti chiedo, se possibile, di segnalarmi sezione per sezione le modifiche che ritieni assolutamente necessarie in modo da fare una review incrementale e discuterne insieme.

Nessun problema; questa sera compilo una lista con le modifiche che consiglio di più e la allego come commento qui.

2021-01-28 14:34 UTC, carmelolg commented
> Nessun problema; questa sera compilo una lista con le modifiche che consiglio di più e la allego come commento qui.

Sì, direi di dividere in più patch la tua modifica, così magari qualcuna sale subito le altre ci ragioniamo

2021-01-28 14:51 UTC, closed without merging